; Brandon Ponce Aragon
; Practica 2
; Rotabit

    
    
#include "p16F628.inc"
; CONSTANTES
const1   EQU 0X05 ; CONST 1 VALOR 5 EN DECIMAL.
const2   EQU 0XFF
const3   EQU 0XFF
const_port EQU 0X01
; VARIABLES
arch1   EQU 0X20	
arch2   EQU 0X21	
arch3   EQU 0X22   
S0	EQU 0x21
S1	EQU 0x22
S2	EQU 0x23


; CONFIG
; __config 0xFF18
 __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_OFF & _MCLRE_ON & _BOREN_OFF & _LVP_OFF & _CPD_OFF & _CP_OFF


RES_VECT  CODE    0x0000            ; processor reset vector
    GOTO    START                   ; go to beginning of program

; TODO ADD INTERRUPTS HERE IF USED

MAIN_PROG CODE                      ; let linker place main program

START
 ;***** PORT CONFIG****
    

    BSF STATUS,RP0 ; CLEARS 
    BCF STATUS,RP1 ; CLEARS
    CLRF TRISB ; CLEARS TRISB TO USE PORTB AS OUTPUT
    BCF STATUS,RP0 ; RETURNS TO BANK 0 CLEARING BANK 1
    MOVLW const_port ; MOVES 1 TO WORK REGISTRY 
    MOVWF PORTB	;MOVES 1 VALUE TO PORTB 
    ;****END PORT CONFIG******
   
    
    ;***APPLIED FUNCTION***
DERECHA		  
    RRF	    PORTB   ; NOW ROTATES VALUE OF PORTB TO THE RIGHT 
    CALL    DELAY   ; CALLS THE DELAY FUNCTION
    BTFSS   PORTB,0 ; EVALUATES IF THE BIT 0 IN PORTB RETURNS A LOGIC 1
    GOTO    DERECHA	; CREATES A LOOP UNTIL PREVIOUS INSTRUCTION RETURNS A 1 
   
        
IZQUIERDA		  
    RLF	    PORTB   ; ROTATES CURRENT VALUE IN PORTB TO THE LEFT 
    CALL    DELAY   ; CALLS DELAY FUNCTION 
    BTFSS   PORTB,7 ; THIS INSTRUCTIONS WORKS AS AN IF, IT EXPECTS THE BIT 7 IN PORT B TO RETURN A LOGIC 1 TO SKIP TO THE IZQUIERDA FUNCTION
    GOTO    IZQUIERDA ; CALLS IZQUIERDA FUNCTION
    GOTO    DERECHA ; LOOPS DERECHA FUNCTION 
DELAY
    MOVLW 0xFF	; SETS THE WORKING REGISTRY WITH A VALUE OF 255
    MOVWF S0 ; MOVES THE 255 TO FILE R0
    MOVWF S1 ; MOVES 255 TO R1
    MOVLW 0x02 ; CHANGES VALUE OF WORKING REGISTRY TO NUMBER 2 
    MOVWF S2 ; SETS R2 WITH A 0X02 VALUE 
ADD
    DECFSZ S0 ; STARTS DECREASING R0
    GOTO ADD ; CREATES THE LOOP 
    DECFSZ S1 ; DECREASES R1
    GOTO ADD ; CREATES LOOP
    DECFSZ S2 ; DECREASES R2
    GOTO ADD ; CREATES LOOP 
    RETURN
    END